server {
	listen 443 ssl;
	server_name znajdaou.42.fr;

	ssl_certificate     /etc/nginx/ssl/cert.pem;
	ssl_certificate_key /etc/nginx/ssl/key.pem;
	ssl_protocols       TLSv1.2 TLSv1.3;

	root /var/www/html;
	index index.php;

	location /static {
		rewrite ^/static$ / break;
		proxy_pass http://static_page:8987/;
	}

	location /adminer {
		rewrite ^/adminer$ / break;
		proxy_pass http://adminer:8080/;
	}

	location /kuma {
		rewrite ^/kuma$ / break;
		proxy_pass http://uptime_kuma:3001/;
	
	}

	location / {
		try_files $uri $uri/ /index.php?$args;
	}

	location ~ \.php$ {
		fastcgi_pass wordpress:9000;
		include fastcgi_params;
		fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
	}
}

server {
  listen 443 ssl;
  server_name kuma.znajdaou.42.fr;

  ssl_certificate     /etc/nginx/ssl/cert.pem;
  ssl_certificate_key /etc/nginx/ssl/key.pem;
  ssl_protocols       TLSv1.2 TLSv1.3;

  location / {
    proxy_pass http://uptime_kuma:3001;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
  }
}

server {
  listen 443 ssl;
  server_name adminer.znajdaou.42.fr;
  ssl_certificate     /etc/nginx/ssl/cert.pem;
  ssl_certificate_key /etc/nginx/ssl/key.pem;
  ssl_protocols       TLSv1.2 TLSv1.3;

  location / {
    proxy_pass http://adminer:8080;
  }
}

server {
  listen 443 ssl;
  server_name static.znajdaou.42.fr;
  ssl_certificate     /etc/nginx/ssl/cert.pem;
  ssl_certificate_key /etc/nginx/ssl/key.pem;
  ssl_protocols       TLSv1.2 TLSv1.3;

  location / {
    proxy_pass http://static_page:8987;
  }
}
