services:
  mariadb:
    image: mariadb
    hostname: mariadb
    secrets:
      - db_root_password
      - db_password
      - kuma_db_password
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - path: ./.env
        required: true # default 
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always
  wordpress:
    image: wordpress
    hostname: wordpress
    secrets:
      - db_root_password
      - db_password
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    restart: always
    env_file:
      - path: ./.env
        required: true # default
    depends_on:
      - mariadb
      - redis
    healthcheck:
      test: [ "CMD", "test", "-f", "/var/www/html/wp-config.php" ]
      interval: 3s
      timeout: 2s
      retries: 10
      start_period: 5s
  nginx:
    hostname: nginx
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file:
      - path: ./.env
        required: true
    ports:
      - "443:443"
    networks:
      wp_network:
        aliases:
          - ${DOMAIN_NAME}
      bridge: {}
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
  # bonus
  redis:
    image: redis
    hostname: redis
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    env_file:
      - path: ./.env
        required: true
    networks:
      - wp_network
  ftp_server:
    image: ftp_server
    hostname: ftp_server
    build: ./requirements/bonus/ftp_server
    container_name: ftp_server
    env_file:
      - path: ./.env
        required: true
    secrets:
      - ftp_password
    depends_on:
      wordpress:
        condition: service_healthy
    volumes:
      - wordpress_data:$FTP_HOME_DIR
    restart: always
    networks:
      - bridge
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
  static_page:
    image: static_page
    hostname: static_page
    build: ./requirements/bonus/static_page
    container_name: static_page
    env_file:
      - path: ./.env
        required: true
    networks:
      - wp_network
    restart: always
    depends_on:
      - nginx
  adminer:
    image: adminer
    hostname: adminer
    build: ./requirements/bonus/adminer
    container_name: adminer
    restart: always
    depends_on:
      - mariadb
    networks:
      - wp_network
  uptime_kuma:
    image: uptime_kuma
    hostname: uptime_kuma
    build: ./requirements/bonus/uptime_kuma
    container_name: uptime_kuma
    restart: always
    networks:
      - wp_network
    depends_on:
      - nginx

networks:
  wp_network:
    driver: bridge
    internal: true
    name: wp_network
  bridge:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USERNAME/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USERNAME/data/wordpress_data
      o: bind
  # bonus

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  kuma_db_password:
    file: ../secrets/kuma_db_password.txt
