services:
  mariadb:
    hostname: mariadb
    secrets:
      - db_root_password
      - db_password
    build: ./requirements/mariadb
    container_name: mariadb
    env_file:
      - path: ./.env
        required: true # default 
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - wp_network
    restart: always
  wordpress:
    hostname: wordpress
    secrets:
      - db_root_password
      - db_password
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - wp_network
    restart: always
    env_file:
      - path: ./.env
        required: true # default
    depends_on:
      - mariadb
  nginx:
    hostname: nginx
    build: ./requirements/nginx
    container_name: nginx
    env_file:
      - path: ./.env
        required: true
    ports:
      - "443:443"
    networks:
      - wp_network
      - bridge
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress

networks:
  wp_network:
    driver: bridge
    internal: true
    name: wp_network
  bridge:
    driver: bridge

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USERNAME/data/mariadb_data
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/$USERNAME/data/wordpress_data
      o: bind

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
