server {
    listen 8987;
    host 0.0.0.0;
    server_name znajdaou.42.fr/static;
    root ./www;
    index index.html;
    autoindex off;

    location / {
        allow_methods GET;
        index index.html;
        autoindex off;
    }
}
