bind 0.0.0.0
protected-mode no
port 6379

daemonize no
loglevel notice
logfile ""

maxmemory 100mb
maxmemory-policy allkeys-lru

# pure object cache — no durability needed, WordPress just repopulates it
save ""
appendonly no